version: '3'
services:
  db:
    image: postgres
    volumes:
      - covid_backend:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
    environment:
      DATABSE_HOST: db
      DATABSE_USER: postgres
      DATABSE_PASS: postgres

volumes:
  covid_backend:
